/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.shims;

import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CCSTlogo = new javax.swing.JLabel();
        CCSTname = new javax.swing.JLabel();
        ProjectName = new javax.swing.JLabel();
        Schoolportal = new javax.swing.JLabel();
        LGText = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        LoginText = new javax.swing.JLabel();
        AccT = new javax.swing.JTextField();
        PassText = new javax.swing.JLabel();
        PassT = new javax.swing.JPasswordField();
        ShowPassB = new javax.swing.JCheckBox();
        LoginButton = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BGLZ = new javax.swing.JLabel();
        Contacts = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        LGB = new javax.swing.JLabel();
        BGG = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(CCSTlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        CCSTname.setFont(new java.awt.Font("Serif", 1, 45)); // NOI18N
        CCSTname.setForeground(new java.awt.Color(255, 255, 255));
        CCSTname.setText("Clark College of Science and Technology");
        getContentPane().add(CCSTname, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, -1, -1));

        ProjectName.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        ProjectName.setForeground(new java.awt.Color(255, 255, 255));
        ProjectName.setText("School Horizon Information Management System");
        getContentPane().add(ProjectName, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, -1));

        Schoolportal.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        Schoolportal.setForeground(new java.awt.Color(255, 255, 255));
        Schoolportal.setText("SCHOOL PORTAL");
        getContentPane().add(Schoolportal, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, -1, -1));

        LGText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LGText.setText("Login to your account");
        getContentPane().add(LGText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 260, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 293, 260, 20));

        LoginText.setText("Account ");
        getContentPane().add(LoginText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 310, -1, -1));

        AccT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccTActionPerformed(evt);
            }
        });
        getContentPane().add(AccT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 330, 210, 40));

        PassText.setText("Password");
        getContentPane().add(PassText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 390, -1, -1));
        getContentPane().add(PassT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 410, 210, 40));

        ShowPassB.setText("Show Password");
        ShowPassB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPassBActionPerformed(evt);
            }
        });
        getContentPane().add(ShowPassB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1760, 470, -1, -1));

        LoginButton.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\OneDrive\\Documents\\Apache Pictures\\login.png")); // NOI18N
        LoginButton.setText("Login");
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
        });
        getContentPane().add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1830, 10, -1, -1));

        jLabel3.setText("1.  Enter your Account Number and ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 860, -1, -1));

        jLabel4.setText("Password then click the \"Login\" button.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 880, -1, -1));

        jLabel5.setText("button at the top right of the screen");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 950, -1, -1));

        jLabel6.setText("2. If you are a new user click the \"Login\"");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 930, -1, -1));

        jLabel7.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\OneDrive\\Documents\\Apache Pictures\\home.png")); // NOI18N
        jLabel7.setText("SHIMS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel8.setText("By clicking the log-in button I recognize ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 520, -1, -1));

        jLabel10.setText("The Clark College of Science and Technology");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 540, 240, -1));

        jLabel9.setText("authority to see and process my personal ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 560, 240, -1));

        jLabel11.setText("data, Privacy Notice and applicable laws.");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 580, 240, -1));

        BGLZ.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\OneDrive\\Documents\\Apache Pictures\\Plain Lapiz Lazuli.jpg")); // NOI18N
        getContentPane().add(BGLZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1920, 170));

        Contacts.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Contacts.setForeground(new java.awt.Color(255, 255, 255));
        Contacts.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\OneDrive\\Documents\\Apache Pictures\\call.png")); // NOI18N
        Contacts.setText("Contact Us");
        Contacts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactsMouseClicked(evt);
            }
        });
        getContentPane().add(Contacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(1710, 670, 90, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("How to log-in");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 780, 120, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 760, 260, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 820, 260, 10));

        LGB.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\OneDrive\\Documents\\Apache Pictures\\Plain Light Khaki.jpg")); // NOI18N
        getContentPane().add(LGB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 250, 260, 760));

        BGG.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\OneDrive\\Documents\\Apache Pictures\\Plain Grey.jpg")); // NOI18N
        getContentPane().add(BGG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 50));

        BG.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\OneDrive\\Documents\\Apache Pictures\\Plain White.jpg")); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccTActionPerformed

    private void ShowPassBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPassBActionPerformed

        if (ShowPassB.isSelected()){
            PassT.setEchoChar((char)0);
        }
        else
        PassT.setEchoChar('*');

        // TODO add your handling code here:
    }//GEN-LAST:event_ShowPassBActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

        if (AccT.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please Fill out Account");
        }

        else if (PassT.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please Fill out Password");

        }

        else if (AccT.getText().contains("admin") && PassT.getText().contains("adminpass")){
            JOptionPane.showMessageDialog(null, "Login Success");

            this.dispose();
            new admin().setVisible(true);

        }

        else {
            JOptionPane.showMessageDialog(null, "Wrong Password or Account Number" , "Login Info" , JOptionPane.ERROR_MESSAGE);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked

 
        new Login().setVisible(true);
        



        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonMouseClicked

    private void ContactsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactsMouseClicked

    
        new Contacts().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_ContactsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccT;
    private javax.swing.JLabel BG;
    private javax.swing.JLabel BGG;
    private javax.swing.JLabel BGLZ;
    private javax.swing.JLabel CCSTlogo;
    private javax.swing.JLabel CCSTname;
    private javax.swing.JLabel Contacts;
    private javax.swing.JLabel LGB;
    private javax.swing.JLabel LGText;
    private javax.swing.JLabel LoginButton;
    private javax.swing.JLabel LoginText;
    private javax.swing.JPasswordField PassT;
    private javax.swing.JLabel PassText;
    private javax.swing.JLabel ProjectName;
    private javax.swing.JLabel Schoolportal;
    private javax.swing.JCheckBox ShowPassB;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton login;
    // End of variables declaration//GEN-END:variables
}
