/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shimsystem;

import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        teacher = new javax.swing.JScrollPane();
        TeacherTable = new javax.swing.JTable();
        panel1 = new java.awt.Panel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        student = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();
        jPanel1 = new java.awt.Panel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        panel3 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sched = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        show = new javax.swing.JButton();
        saves = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ttime = new javax.swing.JTextField();
        ttId = new javax.swing.JTextField();
        ggrade = new javax.swing.JTextField();
        rroom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setVisible(false);
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(0, 204, 204));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("SHOW");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, 150, 50));

        jButton7.setBackground(new java.awt.Color(0, 153, 0));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Add");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 150, 50));

        jButton8.setBackground(new java.awt.Color(204, 0, 0));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Remove");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        panel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 560, 150, 50));

        TeacherTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Teacher Name", "Teacher ID", "Teacher Pasword", "Teacher Gmail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        teacher.setViewportView(TeacherTable);

        panel2.add(teacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 550));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 870, 610));

        panel1.setVisible(false);
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SHOW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, 150, 50));

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 150, 50));

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Remove");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 560, 150, 50));

        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student Name", "Student ID", "Student Pasword", "Student Gmail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        student.setViewportView(StudentTable);

        panel1.add(student, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 550));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 870, 610));

        jPanel1.setVisible(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setText("Teacher Schedule Management");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 210, 60));

        jButton10.setText("List of Teacher Accounts");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Plain White.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 600, 130));

        panel3.setVisible(false);
        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sched.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Teacher ID", "Grade and Section", "Time", "Room"
            }
        ));
        jScrollPane1.setViewportView(sched);

        panel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 360));

        jButton12.setText("Search");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        panel3.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, -1, -1));
        panel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 140, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel10.setText("Room");
        panel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, -1, -1));

        show.setText("SHOW");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        panel3.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 150, 50));

        saves.setText("SAVE");
        saves.setActionCommand("saves");
        saves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savesActionPerformed(evt);
            }
        });
        panel3.add(saves, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 90, 30));

        remove.setText("REMOVE");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        panel3.add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, 150, 50));

        jLabel11.setText("Teacher ID search");
        panel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel12.setText("Input Required Data to Save");
        panel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel13.setText("Teacher ID");
        panel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel14.setText("Grade and Section");
        panel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel15.setText("Time");
        panel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));
        panel3.add(ttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 120, 30));
        panel3.add(ttId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 120, 30));
        panel3.add(ggrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 120, 30));
        panel3.add(rroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 120, 30));

        getContentPane().add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 870, 610));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SHIMS | ADMIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/home.png"))); // NOI18N
        jLabel9.setText("SHIMS");
        jLabel9.setToolTipText("");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 0, -1, 50));

        jButton4.setText("Teacher management");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 260, 60));

        jButton5.setText("Student management");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 260, 60));

        jButton11.setText("Close Panel");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 700, 100, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("|");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 30, 50));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TEACHER PANEL");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, 50));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("STUDENT PANEL");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, -1, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Plain Lapiz Lazuli.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 50));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TEACHER PANEL");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Plain White.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1200, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked


        new HomePage().setVisible(true);
        this.dispose();



        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        panel1.setVisible(true);
        panel2.setVisible(false);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked


                        new teacher1().setVisible(true);
                        this.dispose();

        


        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked


         new student1().setVisible(true);
         this.dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

          DefaultTableModel model = (DefaultTableModel) StudentTable.getModel(); // or studentTable if that's the correct name
    model.setRowCount(0); // Clear existing rows

    String url = "jdbc:mysql://localhost:3306/testdb";
    String dbUsername = "root";
    String dbPassword = "";

    try (
        Connection conn = DriverManager.getConnection(url, dbUsername, dbPassword);
        PreparedStatement pst = conn.prepareStatement("SELECT FullName, StudentNo, Gmail, Password FROM students");
        ResultSet rs = pst.executeQuery()
    ) {
        while (rs.next()) {
            String fullName = rs.getString("FullName");
            String studentNo = rs.getString("StudentNo");
            String password = rs.getString("Password");
            String gmail = rs.getString("Gmail");

            // Match the order of columns
            model.addRow(new Object[]{fullName, studentNo, password, gmail});
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }





        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

         int selectedRow = StudentTable.getSelectedRow(); // or studentTable

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Please select a student to delete.");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) StudentTable.getModel();
    String studentNo = model.getValueAt(selectedRow, 1).toString(); // Student ID column

    int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this student?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    String url = "jdbc:mysql://localhost:3306/testdb";
    String dbUsername = "root";
    String dbPassword = "";

    try (
        Connection conn = DriverManager.getConnection(url, dbUsername, dbPassword);
        PreparedStatement pst = conn.prepareStatement("DELETE FROM students WHERE StudentNo = ?")
    ) {
        pst.setString(1, studentNo);
        int affectedRows = pst.executeUpdate();

        if (affectedRows > 0) {
            model.removeRow(selectedRow);
            JOptionPane.showMessageDialog(null, "Student deleted successfully.");
        } else {
            JOptionPane.showMessageDialog(null, "Failed to delete student.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }

        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        new Signup().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed


         DefaultTableModel model = (DefaultTableModel) TeacherTable.getModel(); // or studentTable if that's the correct name
    model.setRowCount(0); // Clear existing rows
     String url = "jdbc:mysql://localhost:3306/testdb";
    String dbUsername = "root";
    String dbPassword = "";

try (
    Connection conn = DriverManager.getConnection(url, dbUsername, dbPassword);
    PreparedStatement pst = conn.prepareStatement("SELECT user, id, email, password FROM teacher");
    ResultSet rs = pst.executeQuery()
) {
    while (rs.next()) {
        String username = rs.getString("user");
        String teacherId = rs.getString("id");
        String email = rs.getString("email");
        String password = rs.getString("password");

        model.addRow(new Object[]{username, teacherId, email, password});
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

          new Signup().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed


         int selectedRow = TeacherTable.getSelectedRow(); // or studentTable

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Please select a Account to delete.");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) TeacherTable.getModel();
    String studentNo = model.getValueAt(selectedRow, 1).toString(); // Student ID column

    int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this Account?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    String url = "jdbc:mysql://localhost:3306/testdb";
    String dbUsername = "root";
    String dbPassword = "";

    try (
        Connection conn = DriverManager.getConnection(url, dbUsername, dbPassword);
        PreparedStatement pst = conn.prepareStatement("DELETE FROM teacher WHERE id = ?")
    ) {
        pst.setString(1, studentNo);
        int affectedRows = pst.executeUpdate();

        if (affectedRows > 0) {
            model.removeRow(selectedRow);
            JOptionPane.showMessageDialog(null, "account deleted successfully.");
        } else {
            JOptionPane.showMessageDialog(null, "Failed to delete account.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        panel1.setVisible(false);
        jPanel1.setVisible(true);



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        jPanel1.setVisible(false);
        panel1.setVisible(false);
        panel2.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        panel3.setVisible(false);
        jPanel1.setVisible(false);
        panel1.setVisible(false);
        panel2.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        panel3.setVisible(true);
        jPanel1.setVisible(false);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void savesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savesActionPerformed
    // Initialize variables
Object grade = "Grade 11";   // For example, could be dynamically set
int room = 101;              // Example room number
int teacherId = 123;         // Example teacher ID
Object time = "8:00 AM";     // Example time

// Ensure that the inputs are valid
if (teacherId == 0 || grade == null || time == null || room == 0) {
    JOptionPane.showMessageDialog(null, "Invalid input values! Ensure all fields are filled correctly.");
    return; // Exit if validation fails
}

String url = "jdbc:mysql://localhost:3306/testdb"; // DB URL
String user = "root";  // DB username
String pass = "";      // DB password

try (Connection conn = DriverManager.getConnection(url, user, pass)) {
    // SQL Insert query
    String sql = "INSERT INTO tl (teacherId, grade, time, room) VALUES (?, ?, ?, ?)";
    try (PreparedStatement pst = conn.prepareStatement(sql)) {
        // Set parameters for the SQL query
        pst.setInt(1, teacherId);                 // Setting teacherId
        pst.setString(2, (String) grade);         // Setting grade (make sure it's a String)
        pst.setString(3, (String) time);          // Setting time (make sure it's a String)
        pst.setInt(4, room);                      // Setting room number

        // Execute the insert operation
        int rowsInserted = pst.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(null, "Recorded successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "Insert failed.");
        }
    }
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "SQL Error: " + e.getMessage());
}




        // TODO add your handling code here:
    }//GEN-LAST:event_savesActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed


       
    JTable sched = new JTable();
    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new Object[]{"Teacher ID", "Grade", "Time", "Room"});
    sched.setModel(model);

    // Load existing schedule from the database
    loadScheduleData(model);

    // Create a Remove button
    JButton removeButton = new JButton("Remove Selected Row");
    removeButton.addActionListener(e -> {
        int selectedRow = sched.getSelectedRow();
        if (selectedRow != -1) {
            int teacherId = (Integer) model.getValueAt(selectedRow, 0);
            int confirm = JOptionPane.showConfirmDialog(null, "Delete selected schedule?", "Confirm", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                model.removeRow(selectedRow);
                remove(teacherId);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row to remove.");
        }
    });

    // Use a JPanel with BorderLayout to stack table and button
    JPanel panel = new JPanel(new BorderLayout());
    panel.add(new JScrollPane(sched), BorderLayout.CENTER);
    panel.add(removeButton, BorderLayout.SOUTH);

    // Show the modal dialog (replaces JFrame)
    JOptionPane.showConfirmDialog(null, panel, "Teacher Schedule", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE);
}

// Method to load data from database
public void loadScheduleData(DefaultTableModel model) {
    String url = "jdbc:mysql://localhost:3306/testdb";
    String user = "root";
    String pass = "";

    try (Connection conn = DriverManager.getConnection(url, user, pass)) {
        String query = "SELECT * FROM tl";
        try (PreparedStatement stmt = conn.prepareStatement(query);
             ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                int teacherId = rs.getInt("teacherId");
                String grade = rs.getString("grade");
                String time = rs.getString("time");
                int room = rs.getInt("room");

                model.addRow(new Object[]{teacherId, grade, time, room});
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error loading data: " + e.getMessage());
    }
}

// Method to remove data from the database
    @Override
    public void remove(int teacherId) {
    String url = "jdbc:mysql://localhost:3306/testdb";
    String user = "root";
    String pass = "";

    try (Connection conn = DriverManager.getConnection(url, user, pass)) {
        String query = "DELETE FROM tl WHERE teacherId = ?";
        try (PreparedStatement stmt = conn.prepareStatement(query)) {
            stmt.setInt(1, teacherId);
            int affectedRows = stmt.executeUpdate();
            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(null, "Schedule deleted successfully.");
            } else {
                JOptionPane.showMessageDialog(null, "No schedule found for deletion.");
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error deleting data: " + e.getMessage());
    }






    


        // TODO add your handling code here:
    }//GEN-LAST:event_removeActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed

 DefaultTableModel model = (DefaultTableModel) sched.getModel(); // or use your actual JTable name
model.setRowCount(0); // Clear existing rows

String url = "jdbc:mysql://localhost:3306/testdb";
String dbUsername = "root";
String dbPassword = "";

try (
    Connection conn = DriverManager.getConnection(url, dbUsername, dbPassword);
    PreparedStatement pst = conn.prepareStatement("SELECT teacherId, grade, time, room FROM tl");
    ResultSet rs = pst.executeQuery()
) {
    while (rs.next()) {
        String teacherId = rs.getString("teacherId");
        String grade = rs.getString("grade");
        String time = rs.getString("time");
        String room = rs.getString("room");

        // Match the order of columns
        model.addRow(new Object[]{teacherId, grade, time, room});
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}





        // TODO add your handling code here:
    }//GEN-LAST:event_showActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable StudentTable;
    private javax.swing.JTable TeacherTable;
    private javax.swing.JTextField ggrade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.Panel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private javax.swing.JButton remove;
    private javax.swing.JTextField rroom;
    private javax.swing.JButton saves;
    private javax.swing.JTable sched;
    private javax.swing.JButton show;
    private javax.swing.JScrollPane student;
    private javax.swing.JScrollPane teacher;
    private javax.swing.JTextField ttId;
    private javax.swing.JTextField ttime;
    // End of variables declaration//GEN-END:variables

    private void saveTeacherScheduleData(int teacherId, String grade, int time, int room) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
