/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shimsystem;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author dell
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        teacher = new javax.swing.JScrollPane();
        TeacherTable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabel25 = new javax.swing.JLabel();
        Search1 = new javax.swing.JButton();
        SearchT1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        student = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new java.awt.Panel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        panel3 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sched = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        show = new javax.swing.JButton();
        saves = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ttime = new javax.swing.JTextField();
        ttId = new javax.swing.JTextField();
        ggrade = new javax.swing.JTextField();
        rroom = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        SearchT = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setVisible(false);
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(0, 204, 204));
        jButton6.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("SHOW");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 220, 220, 70));

        jButton7.setBackground(new java.awt.Color(0, 153, 0));
        jButton7.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Add");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 350, 220, 70));

        jButton8.setBackground(new java.awt.Color(204, 0, 0));
        jButton8.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Remove");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        panel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 480, 220, 70));

        TeacherTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Teacher Name", "Teacher ID", "Teacher Pasword", "Teacher Gmail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        teacher.setViewportView(TeacherTable);

        panel2.add(teacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1240, 910));

        jLabel11.setFont(new java.awt.Font("Serif", 1, 40)); // NOI18N
        jLabel11.setText("Teacher List");
        panel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 70, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Plain White.jpg"))); // NOI18N
        panel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 920));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 1550, 910));

        panel1.setVisible(false);
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel25.setText("Input User ID to Search");
        panel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 670, 210, 60));

        Search1.setBackground(new java.awt.Color(0, 51, 204));
        Search1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Search1.setForeground(new java.awt.Color(255, 255, 255));
        Search1.setText("Search");
        Search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search1ActionPerformed(evt);
            }
        });
        panel1.add(Search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 510, 260, 70));

        SearchT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchT1ActionPerformed(evt);
            }
        });
        panel1.add(SearchT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 620, 260, 60));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SHOW");
        jButton1.setMaximumSize(new java.awt.Dimension(111, 39));
        jButton1.setMinimumSize(new java.awt.Dimension(111, 39));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 180, 260, 70));

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add");
        jButton2.setMaximumSize(new java.awt.Dimension(111, 39));
        jButton2.setMinimumSize(new java.awt.Dimension(111, 39));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 400, 260, 70));

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Remove");
        jButton3.setMaximumSize(new java.awt.Dimension(111, 39));
        jButton3.setMinimumSize(new java.awt.Dimension(111, 39));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 290, 260, 70));

        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student Name", "Student ID", "Student Pasword", "Student Gmail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        student.setViewportView(StudentTable);

        panel1.add(student, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 920));

        jLabel22.setFont(new java.awt.Font("Serif", 0, 40)); // NOI18N
        jLabel22.setText("Student List");
        panel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 80, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Plain White.jpg"))); // NOI18N
        panel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 920));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 1530, 920));

        jPanel1.setVisible(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setBackground(new java.awt.Color(51, 51, 51));
        jButton9.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Teacher Schedule Management");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 330, 110));

        jButton10.setBackground(new java.awt.Color(51, 51, 51));
        jButton10.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("List of Teacher Accounts");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 330, 110));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Plain White.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 1020, 440));

        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sched.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Teacher ID", "Grade and Section", "Time", "Room"
            }
        ));
        jScrollPane1.setViewportView(sched);

        panel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 550));

        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel10.setText("Room");
        panel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 700, -1, -1));

        show.setBackground(new java.awt.Color(0, 204, 51));
        show.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        show.setForeground(new java.awt.Color(255, 255, 255));
        show.setText("SHOW");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        panel3.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 80, 150, 50));

        saves.setBackground(new java.awt.Color(0, 204, 0));
        saves.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        saves.setForeground(new java.awt.Color(255, 255, 255));
        saves.setText("SAVE");
        saves.setActionCommand("saves");
        saves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savesActionPerformed(evt);
            }
        });
        panel3.add(saves, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 740, 140, 50));

        remove.setBackground(new java.awt.Color(204, 0, 0));
        remove.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        remove.setForeground(new java.awt.Color(255, 255, 255));
        remove.setText("REMOVE");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        panel3.add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 200, 150, 50));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel12.setText("Input Required Data to Save");
        panel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel13.setText("Teacher ID");
        panel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel14.setText("Grade and Section");
        panel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 700, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel15.setText("Time");
        panel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 700, -1, -1));
        panel3.add(ttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 740, 210, 50));
        panel3.add(ttId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 740, 210, 50));
        panel3.add(ggrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 740, 210, 50));
        panel3.add(rroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 740, 210, 50));

        Search.setBackground(new java.awt.Color(0, 51, 204));
        Search.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        panel3.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 300, 150, 50));
        panel3.add(SearchT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 390, 180, 50));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel24.setText("Input User ID to Search");
        panel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 360, 190, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Plain White.jpg"))); // NOI18N
        panel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, 910));

        getContentPane().add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 1520, 910));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SHIMS | ADMIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 60));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/home.png"))); // NOI18N
        jLabel9.setText("SHIMS");
        jLabel9.setToolTipText("");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1780, 0, -1, 60));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Grad pic.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 330, 380));

        jLabel20.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel20.setText("Student Management");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 427, -1, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/titcher.png"))); // NOI18N
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 340, 420));

        jLabel18.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel18.setText("Teacher Management");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 920, -1, 50));

        jButton11.setBackground(new java.awt.Color(204, 0, 0));
        jButton11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Close Panel");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1690, 990, 190, 50));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("|");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 0, 70, 60));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TEACHER PANEL");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 230, 60));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("STUDENT PANEL");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1487, 0, 220, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Plain Lapiz Lazuli.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 60));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TEACHER PANEL");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Plain White.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1920, 1030));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked


        new HomePage().setVisible(true);
        this.dispose();



        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked


                        new teacher().setVisible(true);
                        this.dispose();

        


        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked


         new student().setVisible(true);
         this.dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

          DefaultTableModel model = (DefaultTableModel) StudentTable.getModel(); // or studentTable if that's the correct name
    model.setRowCount(0); // Clear existing rows

    String url = "jdbc:mysql://localhost:3306/testdb";
    String dbUsername = "root";
    String dbPassword = "";

    try (
        Connection conn = DriverManager.getConnection(url, dbUsername, dbPassword);
        PreparedStatement pst = conn.prepareStatement("SELECT FullName, StudentNo, Gmail, Password FROM students");
        ResultSet rs = pst.executeQuery()
    ) {
        while (rs.next()) {
            String fullName = rs.getString("FullName");
            String studentNo = rs.getString("StudentNo");
            String password = rs.getString("Password");
            String gmail = rs.getString("Gmail");

            // Match the order of columns
            model.addRow(new Object[]{fullName, studentNo, password, gmail});
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }





        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

         int selectedRow = StudentTable.getSelectedRow(); // or studentTable

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Please select a student to delete.");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) StudentTable.getModel();
    String studentNo = model.getValueAt(selectedRow, 1).toString(); // Student ID column

    int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this student?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    String url = "jdbc:mysql://localhost:3306/testdb";
    String dbUsername = "root";
    String dbPassword = "";

    try (
        Connection conn = DriverManager.getConnection(url, dbUsername, dbPassword);
        PreparedStatement pst = conn.prepareStatement("DELETE FROM students WHERE StudentNo = ?")
    ) {
        pst.setString(1, studentNo);
        int affectedRows = pst.executeUpdate();

        if (affectedRows > 0) {
            model.removeRow(selectedRow);
            JOptionPane.showMessageDialog(null, "Student deleted successfully.");
        } else {
            JOptionPane.showMessageDialog(null, "Failed to delete student.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }

        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        new Signup().setVisible(true);
      
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed


         DefaultTableModel model = (DefaultTableModel) TeacherTable.getModel(); // or studentTable if that's the correct name
    model.setRowCount(0); // Clear existing rows
     String url = "jdbc:mysql://localhost:3306/testdb";
    String dbUsername = "root";
    String dbPassword = "";

try (
    Connection conn = DriverManager.getConnection(url, dbUsername, dbPassword);
    PreparedStatement pst = conn.prepareStatement("SELECT user, id, email, password FROM teacher");
    ResultSet rs = pst.executeQuery()
) {
    while (rs.next()) {
        String username = rs.getString("user");
        String teacherId = rs.getString("id");
        String email = rs.getString("email");
        String password = rs.getString("password");

        model.addRow(new Object[]{username, teacherId, email, password});
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

          new Signup().setVisible(true);
   
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed


         int selectedRow = TeacherTable.getSelectedRow(); // or studentTable

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Please select a Account to delete.");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) TeacherTable.getModel();
    String studentNo = model.getValueAt(selectedRow, 1).toString(); // Student ID column

    int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this Account?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    String url = "jdbc:mysql://localhost:3306/testdb";
    String dbUsername = "root";
    String dbPassword = "";

    try (
        Connection conn = DriverManager.getConnection(url, dbUsername, dbPassword);
        PreparedStatement pst = conn.prepareStatement("DELETE FROM teacher WHERE id = ?")
    ) {
        pst.setString(1, studentNo);
        int affectedRows = pst.executeUpdate();

        if (affectedRows > 0) {
            model.removeRow(selectedRow);
            JOptionPane.showMessageDialog(null, "account deleted successfully.");
        } else {
            JOptionPane.showMessageDialog(null, "Failed to delete account.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        jPanel1.setVisible(false);
        panel1.setVisible(false);
        panel2.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        panel3.setVisible(false);
        jPanel1.setVisible(false);
        panel1.setVisible(false);
        panel2.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        panel3.setVisible(true);
        jPanel1.setVisible(false);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void savesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savesActionPerformed
  
    // Read input from JTextFields
    String teacherIdText = ttId.getText().trim();
    String grade = ggrade.getText().trim();
    String time = ttime.getText().trim();
    String roomText = rroom.getText().trim();

    // Validate inputs
    if (teacherIdText.isEmpty() || grade.isEmpty() || time.isEmpty() || roomText.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please fill out all fields!");
        return;
    }

    int teacherId;
    int room;

    try {
        teacherId = Integer.parseInt(teacherIdText);
        room = Integer.parseInt(roomText);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Teacher ID and Room must be valid numbers.");
        return;
    }

    String url = "jdbc:mysql://localhost:3306/testdb";
    String user = "root";
    String pass = "";

    try (Connection conn = DriverManager.getConnection(url, user, pass)) {
        String sql = "INSERT INTO tl (teacherId, grade, time, room) VALUES (?, ?, ?, ?)";
        try (PreparedStatement pst = conn.prepareStatement(sql)) {
            pst.setInt(1, teacherId);
            pst.setString(2, grade);
            pst.setString(3, time);
            pst.setInt(4, room);

            int rowsInserted = pst.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(null, "Recorded successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "Insert failed.");
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "SQL Error: " + e.getMessage());
    }






        // TODO add your handling code here:
    }//GEN-LAST:event_savesActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed

 
 
        int selectedRow = sched.getSelectedRow();  // sched is your JTable

if (selectedRow == -1) {
    JOptionPane.showMessageDialog(null, "Please select a schedule to delete.");
    return;
}

DefaultTableModel model = (DefaultTableModel) sched.getModel();
String teacherId = model.getValueAt(selectedRow, 0).toString(); // Assuming teacherId is in column 0

int confirm = JOptionPane.showConfirmDialog(
        null,
        "Are you sure you want to delete this schedule?",
        "Confirm Deletion",
        JOptionPane.YES_NO_OPTION
);

if (confirm != JOptionPane.YES_OPTION) {
    return;
}

String url = "jdbc:mysql://localhost:3306/testdb";
String dbUsername = "root";
String dbPassword = "";

try (
    Connection conn = DriverManager.getConnection(url, dbUsername, dbPassword);
    PreparedStatement pst = conn.prepareStatement("DELETE FROM tl WHERE teacherId = ?")
) {
    pst.setString(1, teacherId);
    int affectedRows = pst.executeUpdate();

    if (affectedRows > 0) {
        model.removeRow(selectedRow);
        JOptionPane.showMessageDialog(null, "Schedule deleted successfully.");
    } else {
        JOptionPane.showMessageDialog(null, "Failed to delete schedule.");
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}

       


    



        // TODO add your handling code here:
    }//GEN-LAST:event_removeActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed

 DefaultTableModel model = (DefaultTableModel) sched.getModel(); // or use your actual JTable name
model.setRowCount(0); // Clear existing rows

String url = "jdbc:mysql://localhost:3306/testdb";
String dbUsername = "root";
String dbPassword = "";

try (
    Connection conn = DriverManager.getConnection(url, dbUsername, dbPassword);
    PreparedStatement pst = conn.prepareStatement("SELECT teacherId, grade, time, room FROM tl");
    ResultSet rs = pst.executeQuery()
) {
    while (rs.next()) {
        String teacherId = rs.getString("teacherId");
        String grade = rs.getString("grade");
        String time = rs.getString("time");
        String room = rs.getString("room");

        // Match the order of columns
        model.addRow(new Object[]{teacherId, grade, time, room});
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}





        // TODO add your handling code here:
    }//GEN-LAST:event_showActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked

         
        jPanel1.setVisible(true);
        panel1.setVisible(false);
        panel2.setVisible(false);
        panel3.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked

      
        
           
        panel1.setVisible(true);
        panel2.setVisible(false); 
        jPanel1.setVisible(false);
     
        panel3.setVisible(false);

        
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked

        jPanel1.setVisible(false);
        panel1.setVisible(true);
        panel2.setVisible(false);
        panel3.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed

        Search.addActionListener(e -> {
            String teacherIdInput = SearchT.getText().trim();

            if (teacherIdInput.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter a Teacher ID to search.");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) sched.getModel();
            boolean found = false;

            // Loop through the table to find the matching Teacher ID
            for (int i = 0; i < model.getRowCount(); i++) {
                String teacherIdInTable = model.getValueAt(i, 0).toString(); // Assuming teacherId is in column 0

                if (teacherIdInTable.equals(teacherIdInput)) {
                    sched.setRowSelectionInterval(i, i); // Highlight the row
                    sched.scrollRectToVisible(sched.getCellRect(i, 0, true)); // Scroll to the row if it's not visible
                    found = true;
                    break;
                }
            }

            if (!found) {
                JOptionPane.showMessageDialog(null, "No schedule found for Teacher ID: " + teacherIdInput);
            }
        });

        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void Search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search1ActionPerformed
        String studentNoInput = SearchT1.getText().trim();

        if (studentNoInput.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a Student No to search.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) StudentTable.getModel();
        boolean found = false;

        for (int i = 0; i < model.getRowCount(); i++) {
            String studentNoInTable = model.getValueAt(i, 1).toString(); // Column index 1 = Student ID

            if (studentNoInTable.equals(studentNoInput)) {
                StudentTable.setRowSelectionInterval(i, i);
                StudentTable.scrollRectToVisible(StudentTable.getCellRect(i, 0, true));
                found = true;
                break;
            }
        }

        if (!found) {
            JOptionPane.showMessageDialog(null, "No student found with Student No: " + studentNoInput);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_Search1ActionPerformed

    private void SearchT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchT1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Search;
    private javax.swing.JButton Search1;
    private javax.swing.JTextField SearchT;
    private javax.swing.JTextField SearchT1;
    private javax.swing.JTable StudentTable;
    private javax.swing.JTable TeacherTable;
    private javax.swing.JTextField ggrade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.Panel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private javax.swing.JButton remove;
    private javax.swing.JTextField rroom;
    private javax.swing.JButton saves;
    private javax.swing.JTable sched;
    private javax.swing.JButton show;
    private javax.swing.JScrollPane student;
    private javax.swing.JScrollPane teacher;
    private javax.swing.JTextField ttId;
    private javax.swing.JTextField ttime;
    // End of variables declaration//GEN-END:variables

    private void saveTeacherScheduleData(int teacherId, String grade, int time, int room) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
