/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shimsystem;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Connection;
/**
 *
 * @author dell
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        Panel = new java.awt.Panel();
        LoginLeft = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        idField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        roleBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setBackground(new java.awt.Color(153, 153, 153));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        LoginLeft.setPreferredSize(new java.awt.Dimension(393, 400));
        LoginLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        jLabel1.setText("Sign up");
        LoginLeft.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabel2.setText("Password");
        LoginLeft.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 310, -1, -1));
        LoginLeft.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 98, 320, 34));
        LoginLeft.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 338, 320, 32));

        jLabel3.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabel3.setText("Full Name");
        LoginLeft.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 70, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        LoginLeft.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 88, 41));

        jLabel4.setText("I've have an account");
        LoginLeft.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        LoginLeft.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 88, -1));
        LoginLeft.add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 178, 320, 34));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabel5.setText("I.D Number");
        LoginLeft.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 150, -1, -1));

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        LoginLeft.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 320, 34));

        jLabel6.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabel6.setText("Gmail account");
        LoginLeft.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 230, -1, -1));

        roleBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Teacher" }));
        LoginLeft.add(roleBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 80, -1));

        getContentPane().add(LoginLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 390, 540));

        jLabel10.setFont(new java.awt.Font("Segoe UI Historic", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("JOIN US ON ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 400, 80));

        jLabel14.setFont(new java.awt.Font("Segoe UI Historic", 1, 48)); // NOI18N
        jLabel14.setText("JOIN US ON ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 400, 90));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Create a account");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("to explore new horizon");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Historic", 1, 48)); // NOI18N
        jLabel11.setText("A NEW JOURNEY");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 430, 90));

        jLabel13.setFont(new java.awt.Font("Segoe UI Historic", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("A NEW JOURNEY");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 470, 120));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/logind.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String name = nameField.getText().trim();
String id = idField.getText().trim();
String email = emailField.getText().trim();
String pass = new String(passField.getPassword()).trim();
String selectedRole = (String) roleBox.getSelectedItem();  // Get selected role (Student or Teacher)

if (name.isEmpty() || id.isEmpty() || email.isEmpty() || pass.isEmpty()) {
    JOptionPane.showMessageDialog(null, "All fields are required!", "Validation Error", JOptionPane.WARNING_MESSAGE);
    return;
}

// Define the table name based on the selected role
String tableName = selectedRole.equals("Student") ? "students" : "teacher";  // Table 'teacher' for teachers
String dbUrl = "jdbc:mysql://localhost:3306/testdb";  // The same database for both roles
String dbUser = "root";
String dbPassword = "";

// Prepare SQL queries based on the selected role and table
String insertQuery;
String checkQuery;

if (selectedRole.equals("Student")) {
    insertQuery = "INSERT INTO " + tableName + " (FullName, StudentNo, Gmail, Password) VALUES (?, ?, ?, ?)";
    checkQuery = "SELECT COUNT(*) FROM " + tableName + " WHERE StudentNo = ? OR Gmail = ?";
} else {
    // Teacher-specific queries
    insertQuery = "INSERT INTO " + tableName + " (user, id, email, password) VALUES (?, ?, ?, ?)";
    checkQuery = "SELECT COUNT(*) FROM " + tableName + " WHERE id = ? OR email = ?";
}

try (Connection conn = DriverManager.getConnection(dbUrl, dbUser, dbPassword)) {
    // Check if the user already exists in the chosen table
    PreparedStatement checkStmt = conn.prepareStatement(checkQuery);
    checkStmt.setString(1, id);
    checkStmt.setString(2, email);
    ResultSet checkResult = checkStmt.executeQuery();
    checkResult.next();

    if (checkResult.getInt(1) > 0) {
        JOptionPane.showMessageDialog(null, selectedRole + " ID or Email already registered!", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
        // Insert the new user into the chosen table
        PreparedStatement insertStmt = conn.prepareStatement(insertQuery);
        insertStmt.setString(1, name);
        insertStmt.setString(2, id);
        insertStmt.setString(3, email);
        insertStmt.setString(4, pass);  // Optionally hash this password

        int rowsInserted = insertStmt.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(null, selectedRole + " Successfully Registered!", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Check the selected role and open the corresponding panel
            if (selectedRole.equals("Student")) {
                new student().setVisible(true); // Open the student panel
            } else if (selectedRole.equals("Teacher")) {
                new teacher().setVisible(true); // Open the teacher panel
            }

            this.dispose();  // Close the registration or login form
        }
    }

} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage(), "Register Failed", JOptionPane.ERROR_MESSAGE);
}


    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        new NewLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel LoginLeft;
    private java.awt.Panel Panel;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField idField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JPasswordField passField;
    private javax.swing.JComboBox<String> roleBox;
    // End of variables declaration//GEN-END:variables
}
