/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shimsystem;

/**
 *
 * @author dell
 */
public class student extends javax.swing.JFrame {

    /**
     * Creates new form student
     */
    public student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Grade = new java.awt.Panel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        Grade11 = new java.awt.Panel();
        txt1 = new javax.swing.JTextField();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        jLabel112 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        jLabel115 = new javax.swing.JLabel();
        txt6 = new javax.swing.JTextField();
        jLabel116 = new javax.swing.JLabel();
        txt5 = new javax.swing.JTextField();
        jLabel117 = new javax.swing.JLabel();
        txt8 = new javax.swing.JTextField();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        s18 = new javax.swing.JTextField();
        s19 = new javax.swing.JTextField();
        s20 = new javax.swing.JTextField();
        s21 = new javax.swing.JTextField();
        s22 = new javax.swing.JTextField();
        s23 = new javax.swing.JTextField();
        s24 = new javax.swing.JTextField();
        jLabel120 = new javax.swing.JLabel();
        bt5 = new javax.swing.JButton();
        out123 = new javax.swing.JTextField();
        out6 = new javax.swing.JTextField();
        bt6 = new javax.swing.JButton();
        jLabel121 = new javax.swing.JLabel();
        t18 = new javax.swing.JTextField();
        t19 = new javax.swing.JTextField();
        t20 = new javax.swing.JTextField();
        t21 = new javax.swing.JTextField();
        t22 = new javax.swing.JTextField();
        t23 = new javax.swing.JTextField();
        t24 = new javax.swing.JTextField();
        jLabel131 = new javax.swing.JLabel();
        p18 = new javax.swing.JTextField();
        p19 = new javax.swing.JTextField();
        p20 = new javax.swing.JTextField();
        p21 = new javax.swing.JTextField();
        p22 = new javax.swing.JTextField();
        p23 = new javax.swing.JTextField();
        p24 = new javax.swing.JTextField();
        jLabel132 = new javax.swing.JLabel();
        bt7 = new javax.swing.JButton();
        out7 = new javax.swing.JTextField();
        out8 = new javax.swing.JTextField();
        bt8 = new javax.swing.JButton();
        jLabel133 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        f29 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        txt9 = new javax.swing.JTextField();
        f32 = new javax.swing.JTextField();
        jLabel152 = new javax.swing.JLabel();
        jLabel153 = new javax.swing.JLabel();
        jLabel154 = new javax.swing.JLabel();
        jLabel155 = new javax.swing.JLabel();
        jLabel156 = new javax.swing.JLabel();
        jLabel157 = new javax.swing.JLabel();
        jLabel158 = new javax.swing.JLabel();
        jLabel159 = new javax.swing.JLabel();
        jLabel160 = new javax.swing.JLabel();
        jLabel161 = new javax.swing.JLabel();
        jLabel162 = new javax.swing.JLabel();
        jLabel163 = new javax.swing.JLabel();
        jLabel164 = new javax.swing.JLabel();
        jLabel165 = new javax.swing.JLabel();
        jLabel167 = new javax.swing.JLabel();
        jLabel169 = new javax.swing.JLabel();
        jLabel166 = new javax.swing.JLabel();
        jLabel168 = new javax.swing.JLabel();
        jLabel170 = new javax.swing.JLabel();
        jLabel171 = new javax.swing.JLabel();
        jLabel172 = new javax.swing.JLabel();
        jLabel174 = new javax.swing.JLabel();
        jLabel176 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        Grade12 = new java.awt.Panel();
        t25 = new javax.swing.JTextField();
        t26 = new javax.swing.JTextField();
        t27 = new javax.swing.JTextField();
        t28 = new javax.swing.JTextField();
        t29 = new javax.swing.JTextField();
        t30 = new javax.swing.JTextField();
        t31 = new javax.swing.JTextField();
        jLabel136 = new javax.swing.JLabel();
        p25 = new javax.swing.JTextField();
        p26 = new javax.swing.JTextField();
        p27 = new javax.swing.JTextField();
        p28 = new javax.swing.JTextField();
        p29 = new javax.swing.JTextField();
        p30 = new javax.swing.JTextField();
        p31 = new javax.swing.JTextField();
        jLabel137 = new javax.swing.JLabel();
        bt11 = new javax.swing.JButton();
        out11 = new javax.swing.JTextField();
        out12 = new javax.swing.JTextField();
        bt12 = new javax.swing.JButton();
        jLabel138 = new javax.swing.JLabel();
        jLabel184 = new javax.swing.JLabel();
        jLabel185 = new javax.swing.JLabel();
        jLabel186 = new javax.swing.JLabel();
        jLabel187 = new javax.swing.JLabel();
        jLabel188 = new javax.swing.JLabel();
        jLabel189 = new javax.swing.JLabel();
        jLabel190 = new javax.swing.JLabel();
        jLabel191 = new javax.swing.JLabel();
        jLabel192 = new javax.swing.JLabel();
        jLabel193 = new javax.swing.JLabel();
        jLabel194 = new javax.swing.JLabel();
        jLabel195 = new javax.swing.JLabel();
        jLabel196 = new javax.swing.JLabel();
        jLabel197 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        f11 = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        f12 = new javax.swing.JTextField();
        f14 = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        f13 = new javax.swing.JTextField();
        jLabel79 = new javax.swing.JLabel();
        f16 = new javax.swing.JTextField();
        jLabel80 = new javax.swing.JLabel();
        f15 = new javax.swing.JTextField();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        s17 = new javax.swing.JTextField();
        s16 = new javax.swing.JTextField();
        s15 = new javax.swing.JTextField();
        s14 = new javax.swing.JTextField();
        s13 = new javax.swing.JTextField();
        s12 = new javax.swing.JTextField();
        s11 = new javax.swing.JTextField();
        jLabel91 = new javax.swing.JLabel();
        bt2 = new javax.swing.JButton();
        out1 = new javax.swing.JTextField();
        out2 = new javax.swing.JTextField();
        bt1 = new javax.swing.JButton();
        jLabel113 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        f18 = new javax.swing.JTextField();
        f19 = new javax.swing.JTextField();
        f21 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        College = new java.awt.Panel();
        f44 = new javax.swing.JTextField();
        jLabel130 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        f45 = new javax.swing.JTextField();
        f46 = new javax.swing.JTextField();
        jLabel142 = new javax.swing.JLabel();
        f47 = new javax.swing.JTextField();
        jLabel143 = new javax.swing.JLabel();
        f48 = new javax.swing.JTextField();
        jLabel144 = new javax.swing.JLabel();
        f49 = new javax.swing.JTextField();
        jLabel145 = new javax.swing.JLabel();
        f50 = new javax.swing.JTextField();
        jLabel146 = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        s32 = new javax.swing.JTextField();
        s33 = new javax.swing.JTextField();
        s34 = new javax.swing.JTextField();
        s35 = new javax.swing.JTextField();
        s36 = new javax.swing.JTextField();
        s37 = new javax.swing.JTextField();
        s38 = new javax.swing.JTextField();
        jLabel148 = new javax.swing.JLabel();
        bt13 = new javax.swing.JButton();
        out13 = new javax.swing.JTextField();
        out14 = new javax.swing.JTextField();
        bt14 = new javax.swing.JButton();
        jLabel149 = new javax.swing.JLabel();
        t32 = new javax.swing.JTextField();
        t33 = new javax.swing.JTextField();
        t34 = new javax.swing.JTextField();
        t35 = new javax.swing.JTextField();
        t36 = new javax.swing.JTextField();
        t37 = new javax.swing.JTextField();
        t38 = new javax.swing.JTextField();
        jLabel150 = new javax.swing.JLabel();
        p32 = new javax.swing.JTextField();
        p33 = new javax.swing.JTextField();
        p34 = new javax.swing.JTextField();
        p35 = new javax.swing.JTextField();
        p36 = new javax.swing.JTextField();
        p37 = new javax.swing.JTextField();
        p38 = new javax.swing.JTextField();
        jLabel151 = new javax.swing.JLabel();
        bt15 = new javax.swing.JButton();
        out15 = new javax.swing.JTextField();
        out16 = new javax.swing.JTextField();
        bt16 = new javax.swing.JButton();
        jLabel198 = new javax.swing.JLabel();
        jLabel199 = new javax.swing.JLabel();
        jLabel200 = new javax.swing.JLabel();
        f51 = new javax.swing.JTextField();
        f52 = new javax.swing.JTextField();
        f53 = new javax.swing.JTextField();
        f54 = new javax.swing.JTextField();
        jLabel201 = new javax.swing.JLabel();
        jLabel202 = new javax.swing.JLabel();
        jLabel203 = new javax.swing.JLabel();
        jLabel204 = new javax.swing.JLabel();
        jLabel205 = new javax.swing.JLabel();
        jLabel206 = new javax.swing.JLabel();
        jLabel207 = new javax.swing.JLabel();
        jLabel208 = new javax.swing.JLabel();
        jLabel209 = new javax.swing.JLabel();
        jLabel210 = new javax.swing.JLabel();
        jLabel211 = new javax.swing.JLabel();
        jLabel212 = new javax.swing.JLabel();
        jLabel213 = new javax.swing.JLabel();
        jLabel214 = new javax.swing.JLabel();
        jLabel215 = new javax.swing.JLabel();
        jLabel216 = new javax.swing.JLabel();
        jLabel217 = new javax.swing.JLabel();
        jLabel218 = new javax.swing.JLabel();
        jLabel219 = new javax.swing.JLabel();
        jLabel220 = new javax.swing.JLabel();
        jLabel221 = new javax.swing.JLabel();
        jLabel222 = new javax.swing.JLabel();
        jLabel223 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STUDENT | SHIMS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SHIMS | STUDENT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -3, -1, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/home.png"))); // NOI18N
        jLabel9.setText("SHIMS");
        jLabel9.setToolTipText("");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1830, 0, -1, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Plain Lapiz Lazuli.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 50));

        jButton1.setText("Grade Computer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 250, 60));

        jButton2.setText("Lessons");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 250, 60));

        jButton3.setText("Schedule");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 250, 60));

        jButton4.setText("Enrollment");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 250, 60));

        jButton5.setText("Activities");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 250, 60));

        Grade.setBackground(new java.awt.Color(204, 204, 204));
        Grade.setVisible(false);
        Grade.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        button1.setLabel("College");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        Grade.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 450, 50));

        button2.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        button2.setLabel("Grade 11");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        Grade.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 450, 50));

        button3.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        button3.setLabel("Grade 12");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        Grade.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 450, 50));

        Grade11.setVisible(false);
        Grade11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Grade11.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 100, 40));

        jLabel110.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel110.setText("Subject 1");
        Grade11.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        jLabel111.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel111.setText("Subject 2");
        Grade11.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));
        Grade11.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 100, 40));
        Grade11.add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 100, 40));

        jLabel112.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel112.setText("Subject 7");
        Grade11.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 170, -1, -1));
        Grade11.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 100, 40));

        jLabel115.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel115.setText("Subject 3");
        Grade11.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, 20));
        Grade11.add(txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 100, 40));

        jLabel116.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel116.setText("Subject 6");
        Grade11.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, -1, -1));
        Grade11.add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 100, 40));

        jLabel117.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel117.setText("Subject 8");
        Grade11.add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 170, -1, -1));
        Grade11.add(txt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 200, 100, 40));

        jLabel118.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel118.setText("Subject 5");
        jLabel118.setToolTipText("");
        Grade11.add(jLabel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, -1, -1));

        jLabel119.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel119.setText("First Quarter");
        jLabel119.setToolTipText("");
        Grade11.add(jLabel119, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
        Grade11.add(s18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 310, 100, 40));
        Grade11.add(s19, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 310, 100, 40));
        Grade11.add(s20, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, 100, 40));
        Grade11.add(s21, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 100, 40));
        Grade11.add(s22, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 100, 40));
        Grade11.add(s23, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 100, 40));
        Grade11.add(s24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 100, 40));

        jLabel120.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel120.setText("Second Quarter");
        Grade11.add(jLabel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        bt5.setText("Calculate Second Quarter");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        Grade11.add(bt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 280, -1, -1));

        out123.setEditable(false);
        out123.setToolTipText("");
        out123.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                out123ActionPerformed(evt);
            }
        });
        Grade11.add(out123, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 200, 83, 32));

        out6.setEditable(false);
        out6.setToolTipText("");
        Grade11.add(out6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 330, 83, 32));

        bt6.setText("Calculate First Quarter");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        Grade11.add(bt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 160, -1, -1));

        jLabel121.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel121.setText("First Semester");
        Grade11.add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 260, -1));
        Grade11.add(t18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 100, 40));
        Grade11.add(t19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 100, 40));
        Grade11.add(t20, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 100, 40));
        Grade11.add(t21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 100, 40));
        Grade11.add(t22, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, 100, 40));
        Grade11.add(t23, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, 100, 40));
        Grade11.add(t24, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 500, 100, 40));

        jLabel131.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel131.setText("First Quarter");
        jLabel131.setToolTipText("");
        Grade11.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));
        Grade11.add(p18, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 620, 100, 40));
        Grade11.add(p19, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 620, 100, 40));
        Grade11.add(p20, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 620, 100, 40));
        Grade11.add(p21, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 620, 100, 40));
        Grade11.add(p22, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, 100, 40));
        Grade11.add(p23, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 620, 100, 40));
        Grade11.add(p24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, 100, 40));

        jLabel132.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel132.setText("Second Quarter");
        Grade11.add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, -1, -1));

        bt7.setText("Calculate Second Quarter");
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });
        Grade11.add(bt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 580, -1, -1));

        out7.setEditable(false);
        out7.setToolTipText("");
        Grade11.add(out7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 510, 83, 32));

        out8.setEditable(false);
        out8.setToolTipText("");
        Grade11.add(out8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 610, 83, 32));

        bt8.setText("Calculate First Quarter");
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });
        Grade11.add(bt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 460, -1, -1));

        jLabel133.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel133.setText("Second Semester");
        Grade11.add(jLabel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 320, -1));

        jLabel134.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel134.setText("Subject 9");
        Grade11.add(jLabel134, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 170, -1, 20));

        jLabel135.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel135.setText("Subject 4");
        Grade11.add(jLabel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, -1, -1));
        Grade11.add(f29, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 100, 40));
        Grade11.add(txt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 200, 100, 40));
        Grade11.add(txt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 200, 100, 40));
        Grade11.add(f32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 310, 100, 40));

        jLabel152.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel152.setText("Subject 1");
        Grade11.add(jLabel152, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        jLabel153.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel153.setText("Subject 2");
        Grade11.add(jLabel153, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        jLabel154.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel154.setText("Subject 7");
        Grade11.add(jLabel154, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 280, -1, -1));

        jLabel155.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel155.setText("Subject 3");
        Grade11.add(jLabel155, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, 20));

        jLabel156.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel156.setText("Subject 6");
        Grade11.add(jLabel156, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 280, -1, -1));

        jLabel157.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel157.setText("Subject 8");
        Grade11.add(jLabel157, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 280, -1, -1));

        jLabel158.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel158.setText("Subject 5");
        jLabel158.setToolTipText("");
        Grade11.add(jLabel158, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, -1, -1));

        jLabel159.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel159.setText("Subject 9");
        Grade11.add(jLabel159, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 280, -1, 20));

        jLabel160.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel160.setText("Subject 4");
        Grade11.add(jLabel160, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        jLabel161.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel161.setText("Subject 1");
        Grade11.add(jLabel161, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, -1));

        jLabel162.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel162.setText("Subject 2");
        Grade11.add(jLabel162, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, -1, -1));

        jLabel163.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel163.setText("Subject 7");
        Grade11.add(jLabel163, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 470, -1, -1));

        jLabel164.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel164.setText("Subject 3");
        Grade11.add(jLabel164, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, -1, 20));

        jLabel165.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel165.setText("Subject 6");
        Grade11.add(jLabel165, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, -1, -1));

        jLabel167.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel167.setText("Subject 5");
        jLabel167.setToolTipText("");
        Grade11.add(jLabel167, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, -1, -1));

        jLabel169.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel169.setText("Subject 4");
        Grade11.add(jLabel169, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, -1, -1));

        jLabel166.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel166.setText("Subject 1");
        Grade11.add(jLabel166, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, -1, -1));

        jLabel168.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel168.setText("Subject 2");
        Grade11.add(jLabel168, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, -1, -1));

        jLabel170.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel170.setText("Subject 7");
        Grade11.add(jLabel170, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 590, -1, -1));

        jLabel171.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel171.setText("Subject 3");
        Grade11.add(jLabel171, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, -1, 20));

        jLabel172.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel172.setText("Subject 6");
        Grade11.add(jLabel172, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 590, -1, -1));

        jLabel174.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel174.setText("Subject 5");
        jLabel174.setToolTipText("");
        Grade11.add(jLabel174, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 590, -1, -1));

        jLabel176.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel176.setText("Subject 4");
        Grade11.add(jLabel176, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 590, -1, -1));

        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Grade11.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 10, 100, 30));

        Grade.add(Grade11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1590, 950));

        Grade12.setVisible(false);
        Grade12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Grade12.add(t25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 100, 40));
        Grade12.add(t26, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 100, 40));
        Grade12.add(t27, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 100, 40));
        Grade12.add(t28, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 100, 40));
        Grade12.add(t29, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, 100, 40));
        Grade12.add(t30, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, 100, 40));
        Grade12.add(t31, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 500, 100, 40));

        jLabel136.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel136.setText("First Quarter");
        jLabel136.setToolTipText("");
        Grade12.add(jLabel136, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));
        Grade12.add(p25, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 620, 100, 40));
        Grade12.add(p26, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 620, 100, 40));
        Grade12.add(p27, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 620, 100, 40));
        Grade12.add(p28, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 620, 100, 40));
        Grade12.add(p29, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, 100, 40));
        Grade12.add(p30, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 620, 100, 40));
        Grade12.add(p31, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, 100, 40));

        jLabel137.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel137.setText("Second Quarter");
        Grade12.add(jLabel137, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, -1, -1));

        bt11.setText("Calculate Second Quarter");
        bt11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt11ActionPerformed(evt);
            }
        });
        Grade12.add(bt11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 580, -1, -1));

        out11.setEditable(false);
        out11.setToolTipText("");
        Grade12.add(out11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 510, 83, 32));

        out12.setEditable(false);
        out12.setToolTipText("");
        Grade12.add(out12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 610, 83, 32));

        bt12.setText("Calculate First Quarter");
        bt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt12ActionPerformed(evt);
            }
        });
        Grade12.add(bt12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 460, -1, -1));

        jLabel138.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel138.setText("Second Semester");
        Grade12.add(jLabel138, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 320, -1));

        jLabel184.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel184.setText("Subject 1");
        Grade12.add(jLabel184, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, -1));

        jLabel185.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel185.setText("Subject 2");
        Grade12.add(jLabel185, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, -1, -1));

        jLabel186.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel186.setText("Subject 7");
        Grade12.add(jLabel186, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 470, -1, -1));

        jLabel187.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel187.setText("Subject 3");
        Grade12.add(jLabel187, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, -1, 20));

        jLabel188.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel188.setText("Subject 6");
        Grade12.add(jLabel188, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, -1, -1));

        jLabel189.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel189.setText("Subject 5");
        jLabel189.setToolTipText("");
        Grade12.add(jLabel189, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, -1, -1));

        jLabel190.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel190.setText("Subject 4");
        Grade12.add(jLabel190, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, -1, -1));

        jLabel191.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel191.setText("Subject 1");
        Grade12.add(jLabel191, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, -1, -1));

        jLabel192.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel192.setText("Subject 2");
        Grade12.add(jLabel192, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, -1, -1));

        jLabel193.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel193.setText("Subject 7");
        Grade12.add(jLabel193, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 590, -1, -1));

        jLabel194.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel194.setText("Subject 3");
        Grade12.add(jLabel194, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, -1, 20));

        jLabel195.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel195.setText("Subject 6");
        Grade12.add(jLabel195, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 590, -1, -1));

        jLabel196.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel196.setText("Subject 5");
        jLabel196.setToolTipText("");
        Grade12.add(jLabel196, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 590, -1, -1));

        jLabel197.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel197.setText("Subject 4");
        Grade12.add(jLabel197, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 590, -1, -1));

        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        Grade12.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 20, 100, 30));
        Grade12.add(f11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 100, 40));

        jLabel76.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel76.setText("Empowerment");
        Grade12.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        jLabel77.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel77.setText("Physical");
        Grade12.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));
        Grade12.add(f12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 100, 40));
        Grade12.add(f14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 100, 40));

        jLabel78.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel78.setText("Reading and ");
        Grade12.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 150, -1, -1));
        Grade12.add(f13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 100, 40));

        jLabel79.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel79.setText("Oral ");
        Grade12.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, 20));
        Grade12.add(f16, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 100, 40));

        jLabel80.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel80.setText("21ST Century");
        Grade12.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, -1, -1));
        Grade12.add(f15, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 100, 40));

        jLabel82.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel82.setText("Earth ");
        jLabel82.setToolTipText("");
        Grade12.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, -1, -1));

        jLabel83.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel83.setText("First Quarter");
        jLabel83.setToolTipText("");
        Grade12.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
        Grade12.add(s17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 310, 100, 40));
        Grade12.add(s16, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 310, 100, 40));
        Grade12.add(s15, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, 100, 40));
        Grade12.add(s14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 100, 40));
        Grade12.add(s13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 100, 40));
        Grade12.add(s12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 100, 40));
        Grade12.add(s11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 100, 40));

        jLabel91.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel91.setText("Second Quarter");
        Grade12.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        bt2.setText("Calculate Second Quarter");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        Grade12.add(bt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 280, -1, -1));

        out1.setEditable(false);
        out1.setToolTipText("");
        out1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                out1ActionPerformed(evt);
            }
        });
        Grade12.add(out1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 200, 83, 32));

        out2.setEditable(false);
        out2.setToolTipText("");
        Grade12.add(out2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 330, 83, 32));

        bt1.setText("Calculate First Quarter");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        Grade12.add(bt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 160, -1, -1));

        jLabel113.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel113.setText("First Semester");
        Grade12.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 260, -1));

        jLabel109.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel109.setText("Computer");
        Grade12.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, -1));
        Grade12.add(f18, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 100, 40));
        Grade12.add(f19, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 200, 100, 40));
        Grade12.add(f21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 310, 100, 40));

        jLabel2.setText("Technology");
        Grade12.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        jLabel4.setText("Education");
        Grade12.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        jLabel5.setText("Communication");
        Grade12.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, 10));

        jLabel6.setText("Hardware");
        Grade12.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, -1, -1));

        jLabel7.setText("& Life Science");
        Grade12.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, -1, -1));

        jLabel8.setText("Writing");
        Grade12.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 180, -1, -1));

        jLabel84.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel84.setText("Empowerment");
        Grade12.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        jLabel85.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel85.setText("Physical");
        Grade12.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        jLabel86.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel86.setText("Reading and ");
        Grade12.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 260, -1, -1));

        jLabel87.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel87.setText("Oral ");
        Grade12.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, 20));

        jLabel88.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel88.setText("21ST Century");
        Grade12.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, -1, -1));

        jLabel89.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel89.setText("General ");
        Grade12.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 260, -1, -1));

        jLabel90.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel90.setText("Earth ");
        jLabel90.setToolTipText("");
        Grade12.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, -1, -1));

        jLabel128.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel128.setText("Computer");
        Grade12.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 260, -1, 20));

        jLabel129.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel129.setText("Computer");
        Grade12.add(jLabel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));

        jLabel12.setText("Technology");
        Grade12.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        jLabel13.setText("Education");
        Grade12.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        jLabel14.setText("Communication");
        Grade12.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, 10));

        jLabel15.setText("Hardware");
        Grade12.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, -1, -1));

        jLabel16.setText("& Life Science");
        Grade12.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, -1, -1));

        jLabel17.setText("Writing");
        Grade12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 290, -1, -1));

        jLabel18.setText("Mathematics");
        Grade12.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 290, -1, -1));

        jLabel19.setText("Hardware");
        Grade12.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 290, -1, 10));

        Grade.add(Grade12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1590, 950));

        College.setVisible(false);
        College.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        College.add(f44, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 100, 40));

        jLabel130.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel130.setText("Subject 1");
        College.add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        jLabel141.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel141.setText("Subject 2");
        College.add(jLabel141, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));
        College.add(f45, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 100, 40));
        College.add(f46, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 100, 40));

        jLabel142.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel142.setText("Subject 7");
        College.add(jLabel142, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 170, -1, -1));
        College.add(f47, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 100, 40));

        jLabel143.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel143.setText("Subject 3");
        College.add(jLabel143, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, 20));
        College.add(f48, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 100, 40));

        jLabel144.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel144.setText("Subject 6");
        College.add(jLabel144, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, -1, -1));
        College.add(f49, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 100, 40));

        jLabel145.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel145.setText("Subject 8");
        College.add(jLabel145, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 170, -1, -1));
        College.add(f50, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 200, 100, 40));

        jLabel146.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel146.setText("Subject 5");
        jLabel146.setToolTipText("");
        College.add(jLabel146, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, -1, -1));

        jLabel147.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel147.setText("First Quarter");
        jLabel147.setToolTipText("");
        College.add(jLabel147, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
        College.add(s32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 310, 100, 40));
        College.add(s33, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 310, 100, 40));
        College.add(s34, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, 100, 40));
        College.add(s35, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 100, 40));
        College.add(s36, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 100, 40));
        College.add(s37, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 100, 40));
        College.add(s38, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 100, 40));

        jLabel148.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel148.setText("Second Quarter");
        College.add(jLabel148, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        bt13.setText("Calculate Second Quarter");
        bt13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt13ActionPerformed(evt);
            }
        });
        College.add(bt13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 280, -1, -1));

        out13.setEditable(false);
        out13.setToolTipText("");
        out13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                out13ActionPerformed(evt);
            }
        });
        College.add(out13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 200, 83, 32));

        out14.setEditable(false);
        out14.setToolTipText("");
        College.add(out14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 330, 83, 32));

        bt14.setText("Calculate First Quarter");
        bt14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt14ActionPerformed(evt);
            }
        });
        College.add(bt14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 160, -1, -1));

        jLabel149.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel149.setText("First Semester");
        College.add(jLabel149, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 260, -1));
        College.add(t32, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 100, 40));
        College.add(t33, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 100, 40));
        College.add(t34, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 100, 40));
        College.add(t35, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 100, 40));
        College.add(t36, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, 100, 40));
        College.add(t37, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, 100, 40));
        College.add(t38, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 500, 100, 40));

        jLabel150.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel150.setText("First Quarter");
        jLabel150.setToolTipText("");
        College.add(jLabel150, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));
        College.add(p32, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 620, 100, 40));
        College.add(p33, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 620, 100, 40));
        College.add(p34, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 620, 100, 40));
        College.add(p35, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 620, 100, 40));
        College.add(p36, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, 100, 40));
        College.add(p37, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 620, 100, 40));
        College.add(p38, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, 100, 40));

        jLabel151.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel151.setText("Second Quarter");
        College.add(jLabel151, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, -1, -1));

        bt15.setText("Calculate Second Quarter");
        bt15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt15ActionPerformed(evt);
            }
        });
        College.add(bt15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 580, -1, -1));

        out15.setEditable(false);
        out15.setToolTipText("");
        College.add(out15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 510, 83, 32));

        out16.setEditable(false);
        out16.setToolTipText("");
        College.add(out16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 610, 83, 32));

        bt16.setText("Calculate First Quarter");
        bt16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt16ActionPerformed(evt);
            }
        });
        College.add(bt16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 460, -1, -1));

        jLabel198.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel198.setText("Second Semester");
        College.add(jLabel198, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 320, -1));

        jLabel199.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel199.setText("Subject 9");
        College.add(jLabel199, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 170, -1, 20));

        jLabel200.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel200.setText("Subject 4");
        College.add(jLabel200, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, -1, -1));
        College.add(f51, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 100, 40));
        College.add(f52, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 200, 100, 40));
        College.add(f53, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 200, 100, 40));
        College.add(f54, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 310, 100, 40));

        jLabel201.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel201.setText("Subject 1");
        College.add(jLabel201, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        jLabel202.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel202.setText("Subject 2");
        College.add(jLabel202, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        jLabel203.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel203.setText("Subject 7");
        College.add(jLabel203, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 280, -1, -1));

        jLabel204.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel204.setText("Subject 3");
        College.add(jLabel204, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, 20));

        jLabel205.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel205.setText("Subject 6");
        College.add(jLabel205, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 280, -1, -1));

        jLabel206.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel206.setText("Subject 8");
        College.add(jLabel206, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 280, -1, -1));

        jLabel207.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel207.setText("Subject 5");
        jLabel207.setToolTipText("");
        College.add(jLabel207, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, -1, -1));

        jLabel208.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel208.setText("Subject 9");
        College.add(jLabel208, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 280, -1, 20));

        jLabel209.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel209.setText("Subject 4");
        College.add(jLabel209, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        jLabel210.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel210.setText("Subject 1");
        College.add(jLabel210, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, -1));

        jLabel211.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel211.setText("Subject 2");
        College.add(jLabel211, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, -1, -1));

        jLabel212.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel212.setText("Subject 7");
        College.add(jLabel212, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 470, -1, -1));

        jLabel213.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel213.setText("Subject 3");
        College.add(jLabel213, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, -1, 20));

        jLabel214.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel214.setText("Subject 6");
        College.add(jLabel214, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, -1, -1));

        jLabel215.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel215.setText("Subject 5");
        jLabel215.setToolTipText("");
        College.add(jLabel215, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, -1, -1));

        jLabel216.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel216.setText("Subject 4");
        College.add(jLabel216, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, -1, -1));

        jLabel217.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel217.setText("Subject 1");
        College.add(jLabel217, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, -1, -1));

        jLabel218.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel218.setText("Subject 2");
        College.add(jLabel218, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, -1, -1));

        jLabel219.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel219.setText("Subject 7");
        College.add(jLabel219, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 590, -1, -1));

        jLabel220.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel220.setText("Subject 3");
        College.add(jLabel220, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, -1, 20));

        jLabel221.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel221.setText("Subject 6");
        College.add(jLabel221, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 590, -1, -1));

        jLabel222.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel222.setText("Subject 5");
        jLabel222.setToolTipText("");
        College.add(jLabel222, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 590, -1, -1));

        jLabel223.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel223.setText("Subject 4");
        College.add(jLabel223, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 590, -1, -1));

        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        College.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 30, 100, 30));

        Grade.add(College, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1590, 950));

        getContentPane().add(Grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 1590, 950));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Plain White.jpg"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked

        new HomePage().setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     Grade.setVisible(true);



    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt5ActionPerformed

    private void out123ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_out123ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_out123ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed

        try {
    if (txt1.getText().isEmpty() || txt2.getText().isEmpty() || txt3.getText().isEmpty() ||
        txt4.getText().isEmpty() || txt5.getText().isEmpty() || txt6.getText().isEmpty() ||
        txt7.getText().isEmpty() || txt8.getText().isEmpty() || txt9.getText().isEmpty()) {
        
        javax.swing.JOptionPane.showMessageDialog(this, "You have a missing Grade, Please Input a Grade!");
        return;
    }

    int a = Integer.parseInt(txt1.getText());
    int b = Integer.parseInt(txt2.getText());
    int c = Integer.parseInt(txt3.getText());
    int d = Integer.parseInt(txt4.getText());
    int e = Integer.parseInt(txt5.getText());
    int f = Integer.parseInt(txt6.getText());
    int g = Integer.parseInt(txt7.getText());
    int h = Integer.parseInt(txt8.getText());
    int i = Integer.parseInt(txt9.getText());

    if (a > 100 || b > 100 || c > 100 || d > 100 || e > 100 || f > 100 || g > 100 || h > 100 || i > 100) {
        javax.swing.JOptionPane.showMessageDialog(this, "Grades cannot exceed 100. Please enter valid grades.");
        return;
    }

    // Ensure proper floating-point division
    double result = (a + b + c + d + e + f + g + h + i) / 9.0;
    out123.setText(String.format("", result)); // Display result with 2 decimal places

} catch (NumberFormatException ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please enter valid numbers only!");
}




        // TODO add your handling code here:
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt8ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed


        College.setVisible(true);
                 Grade12.setVisible(false);
                  Grade11.setVisible(false);
button1.setVisible(false);
button2.setVisible(false);
button3.setVisible(false);


        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
 Grade11.setVisible(true);
 Grade12.setVisible(false);
  College.setVisible(false);
button1.setVisible(false);
button2.setVisible(false);
button3.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
 Grade12.setVisible(true);
 Grade11.setVisible(false);
  College.setVisible(false);
button1.setVisible(false);
button2.setVisible(false);
button3.setVisible(false);



        // TODO add your handling code here:
    }//GEN-LAST:event_button3ActionPerformed

    private void bt11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt11ActionPerformed

    private void bt12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt12ActionPerformed

    private void bt13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt13ActionPerformed

    private void out13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_out13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_out13ActionPerformed

    private void bt14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt14ActionPerformed

    private void bt15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt15ActionPerformed

    private void bt16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt16ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
Grade11.setVisible(true);
        Grade.setVisible(true);
button1.setVisible(false);
button2.setVisible(false);
button3.setVisible(false);  
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
Grade12.setVisible(true);
        Grade.setVisible(true);
button1.setVisible(false);
button2.setVisible(false);
button3.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
College.setVisible(false);
        Grade.setVisible(true);
button1.setVisible(true);
button2.setVisible(true);
button3.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        try {
            if (s11.getText().isEmpty() || s12.getText().isEmpty() || s13.getText().isEmpty() ||
                s14.getText().isEmpty() || s15.getText().isEmpty() || s16.getText().isEmpty() ||
                s17.getText().isEmpty()) {

                javax.swing.JOptionPane.showMessageDialog(this, "You have a missing Grade, Please Input a Grade!");
                return;
            }

            int a = Integer.parseInt(s11.getText());
            int b = Integer.parseInt(s12.getText());
            int c = Integer.parseInt(s13.getText());
            int d = Integer.parseInt(s14.getText());
            int e = Integer.parseInt(s15.getText());
            int f = Integer.parseInt(s16.getText());
            int g = Integer.parseInt(s17.getText());
            if (a > 99 || b > 99 || c > 99 || d > 99 || e > 99 || f > 99 || g > 99) {

                javax.swing.JOptionPane.showMessageDialog(this, "Grades cannot exceed 100. Please enter valid grades.");
                return;
            }

            int result = (a + b + c + d + e + f + g) / 7;
            out2.setText(String.valueOf(result));

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter valid numbers only!");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_bt2ActionPerformed

    private void out1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_out1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_out1ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        try {
            if (f11.getText().isEmpty() || f12.getText().isEmpty() || f13.getText().isEmpty() ||
                f14.getText().isEmpty() || f15.getText().isEmpty() || f16.getText().isEmpty() ||
                f19.getText().isEmpty()) {

                javax.swing.JOptionPane.showMessageDialog(this, "You have a missing Grade, Please Input a Grade!");
                return;
            }

            int a = Integer.parseInt(f11.getText());
            int b = Integer.parseInt(f12.getText());
            int c = Integer.parseInt(f13.getText());
            int d = Integer.parseInt(f14.getText());
            int e = Integer.parseInt(f15.getText());
            int f = Integer.parseInt(f16.getText());
            int g = Integer.parseInt(f19.getText());

            if (a > 99 || b > 99 || c > 99 || d > 99 || e > 99 || f > 99 || g > 99) {

                javax.swing.JOptionPane.showMessageDialog(this, "Grades cannot exceed 100. Please enter valid grades.");
                return;
            }

            int result = (a + b + c + d + e + f + g) / 7;
            out1.setText(String.valueOf(result));

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter valid numbers only!");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_bt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private java.awt.Panel College;
    private java.awt.Panel Grade;
    private java.awt.Panel Grade11;
    private java.awt.Panel Grade12;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt11;
    private javax.swing.JButton bt12;
    private javax.swing.JButton bt13;
    private javax.swing.JButton bt14;
    private javax.swing.JButton bt15;
    private javax.swing.JButton bt16;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private javax.swing.JTextField f11;
    private javax.swing.JTextField f12;
    private javax.swing.JTextField f13;
    private javax.swing.JTextField f14;
    private javax.swing.JTextField f15;
    private javax.swing.JTextField f16;
    private javax.swing.JTextField f18;
    private javax.swing.JTextField f19;
    private javax.swing.JTextField f21;
    private javax.swing.JTextField f29;
    private javax.swing.JTextField f32;
    private javax.swing.JTextField f44;
    private javax.swing.JTextField f45;
    private javax.swing.JTextField f46;
    private javax.swing.JTextField f47;
    private javax.swing.JTextField f48;
    private javax.swing.JTextField f49;
    private javax.swing.JTextField f50;
    private javax.swing.JTextField f51;
    private javax.swing.JTextField f52;
    private javax.swing.JTextField f53;
    private javax.swing.JTextField f54;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel163;
    private javax.swing.JLabel jLabel164;
    private javax.swing.JLabel jLabel165;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel167;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel169;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel170;
    private javax.swing.JLabel jLabel171;
    private javax.swing.JLabel jLabel172;
    private javax.swing.JLabel jLabel174;
    private javax.swing.JLabel jLabel176;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel184;
    private javax.swing.JLabel jLabel185;
    private javax.swing.JLabel jLabel186;
    private javax.swing.JLabel jLabel187;
    private javax.swing.JLabel jLabel188;
    private javax.swing.JLabel jLabel189;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel190;
    private javax.swing.JLabel jLabel191;
    private javax.swing.JLabel jLabel192;
    private javax.swing.JLabel jLabel193;
    private javax.swing.JLabel jLabel194;
    private javax.swing.JLabel jLabel195;
    private javax.swing.JLabel jLabel196;
    private javax.swing.JLabel jLabel197;
    private javax.swing.JLabel jLabel198;
    private javax.swing.JLabel jLabel199;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel200;
    private javax.swing.JLabel jLabel201;
    private javax.swing.JLabel jLabel202;
    private javax.swing.JLabel jLabel203;
    private javax.swing.JLabel jLabel204;
    private javax.swing.JLabel jLabel205;
    private javax.swing.JLabel jLabel206;
    private javax.swing.JLabel jLabel207;
    private javax.swing.JLabel jLabel208;
    private javax.swing.JLabel jLabel209;
    private javax.swing.JLabel jLabel210;
    private javax.swing.JLabel jLabel211;
    private javax.swing.JLabel jLabel212;
    private javax.swing.JLabel jLabel213;
    private javax.swing.JLabel jLabel214;
    private javax.swing.JLabel jLabel215;
    private javax.swing.JLabel jLabel216;
    private javax.swing.JLabel jLabel217;
    private javax.swing.JLabel jLabel218;
    private javax.swing.JLabel jLabel219;
    private javax.swing.JLabel jLabel220;
    private javax.swing.JLabel jLabel221;
    private javax.swing.JLabel jLabel222;
    private javax.swing.JLabel jLabel223;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JTextField out1;
    private javax.swing.JTextField out11;
    private javax.swing.JTextField out12;
    private javax.swing.JTextField out123;
    private javax.swing.JTextField out13;
    private javax.swing.JTextField out14;
    private javax.swing.JTextField out15;
    private javax.swing.JTextField out16;
    private javax.swing.JTextField out2;
    private javax.swing.JTextField out6;
    private javax.swing.JTextField out7;
    private javax.swing.JTextField out8;
    private javax.swing.JTextField p18;
    private javax.swing.JTextField p19;
    private javax.swing.JTextField p20;
    private javax.swing.JTextField p21;
    private javax.swing.JTextField p22;
    private javax.swing.JTextField p23;
    private javax.swing.JTextField p24;
    private javax.swing.JTextField p25;
    private javax.swing.JTextField p26;
    private javax.swing.JTextField p27;
    private javax.swing.JTextField p28;
    private javax.swing.JTextField p29;
    private javax.swing.JTextField p30;
    private javax.swing.JTextField p31;
    private javax.swing.JTextField p32;
    private javax.swing.JTextField p33;
    private javax.swing.JTextField p34;
    private javax.swing.JTextField p35;
    private javax.swing.JTextField p36;
    private javax.swing.JTextField p37;
    private javax.swing.JTextField p38;
    private javax.swing.JTextField s11;
    private javax.swing.JTextField s12;
    private javax.swing.JTextField s13;
    private javax.swing.JTextField s14;
    private javax.swing.JTextField s15;
    private javax.swing.JTextField s16;
    private javax.swing.JTextField s17;
    private javax.swing.JTextField s18;
    private javax.swing.JTextField s19;
    private javax.swing.JTextField s20;
    private javax.swing.JTextField s21;
    private javax.swing.JTextField s22;
    private javax.swing.JTextField s23;
    private javax.swing.JTextField s24;
    private javax.swing.JTextField s32;
    private javax.swing.JTextField s33;
    private javax.swing.JTextField s34;
    private javax.swing.JTextField s35;
    private javax.swing.JTextField s36;
    private javax.swing.JTextField s37;
    private javax.swing.JTextField s38;
    private javax.swing.JTextField t18;
    private javax.swing.JTextField t19;
    private javax.swing.JTextField t20;
    private javax.swing.JTextField t21;
    private javax.swing.JTextField t22;
    private javax.swing.JTextField t23;
    private javax.swing.JTextField t24;
    private javax.swing.JTextField t25;
    private javax.swing.JTextField t26;
    private javax.swing.JTextField t27;
    private javax.swing.JTextField t28;
    private javax.swing.JTextField t29;
    private javax.swing.JTextField t30;
    private javax.swing.JTextField t31;
    private javax.swing.JTextField t32;
    private javax.swing.JTextField t33;
    private javax.swing.JTextField t34;
    private javax.swing.JTextField t35;
    private javax.swing.JTextField t36;
    private javax.swing.JTextField t37;
    private javax.swing.JTextField t38;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    // End of variables declaration//GEN-END:variables
}
