/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shimsystem;

/**
 *
 * @author dell
 */
public class student extends javax.swing.JFrame {

    /**
     * Creates new form student
     */
    public student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        GradeComputer = new java.awt.Panel();
        f11 = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        f12 = new javax.swing.JTextField();
        f14 = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        f13 = new javax.swing.JTextField();
        jLabel79 = new javax.swing.JLabel();
        f16 = new javax.swing.JTextField();
        jLabel80 = new javax.swing.JLabel();
        f15 = new javax.swing.JTextField();
        jLabel81 = new javax.swing.JLabel();
        f17 = new javax.swing.JTextField();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        s17 = new javax.swing.JTextField();
        s16 = new javax.swing.JTextField();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        s15 = new javax.swing.JTextField();
        s14 = new javax.swing.JTextField();
        jLabel87 = new javax.swing.JLabel();
        s13 = new javax.swing.JTextField();
        jLabel88 = new javax.swing.JLabel();
        s12 = new javax.swing.JTextField();
        jLabel89 = new javax.swing.JLabel();
        s11 = new javax.swing.JTextField();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        bt2 = new javax.swing.JButton();
        out1 = new javax.swing.JTextField();
        out2 = new javax.swing.JTextField();
        bt1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel113 = new javax.swing.JLabel();
        t11 = new javax.swing.JTextField();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        t12 = new javax.swing.JTextField();
        t14 = new javax.swing.JTextField();
        jLabel94 = new javax.swing.JLabel();
        t13 = new javax.swing.JTextField();
        jLabel95 = new javax.swing.JLabel();
        t16 = new javax.swing.JTextField();
        jLabel96 = new javax.swing.JLabel();
        t15 = new javax.swing.JTextField();
        jLabel97 = new javax.swing.JLabel();
        t17 = new javax.swing.JTextField();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        p17 = new javax.swing.JTextField();
        p16 = new javax.swing.JTextField();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        p15 = new javax.swing.JTextField();
        p14 = new javax.swing.JTextField();
        jLabel103 = new javax.swing.JLabel();
        p13 = new javax.swing.JTextField();
        jLabel104 = new javax.swing.JLabel();
        p12 = new javax.swing.JTextField();
        jLabel105 = new javax.swing.JLabel();
        p11 = new javax.swing.JTextField();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        bt3 = new javax.swing.JButton();
        out3 = new javax.swing.JTextField();
        out4 = new javax.swing.JTextField();
        bt4 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel114 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SHIMS | STUDENT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -3, -1, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/home.png"))); // NOI18N
        jLabel9.setText("SHIMS");
        jLabel9.setToolTipText("");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1830, 0, -1, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Plain Lapiz Lazuli.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 50));

        jButton1.setText("Grade Computer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 250, 60));

        jButton2.setText("Lessons");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 250, 60));

        jButton3.setText("Schedule");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 250, 60));

        jButton4.setText("Enrollment");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 250, 60));

        jButton5.setText("Activities");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 250, 60));

        GradeComputer.setForeground(new java.awt.Color(255, 255, 255));
        GradeComputer.setVisible(false);
        GradeComputer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        GradeComputer.add(f11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 100, 40));

        jLabel76.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel76.setText("1st Subject");
        GradeComputer.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jLabel77.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel77.setText("2nd Subject");
        GradeComputer.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));
        GradeComputer.add(f12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 100, 40));
        GradeComputer.add(f14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 100, 40));

        jLabel78.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel78.setText("4th Subject");
        GradeComputer.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, -1));
        GradeComputer.add(f13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 100, 40));

        jLabel79.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel79.setText("3rd Subject");
        GradeComputer.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));
        GradeComputer.add(f16, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 100, 40));

        jLabel80.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel80.setText("6th Subject");
        GradeComputer.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, -1, -1));
        GradeComputer.add(f15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 100, 40));

        jLabel81.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel81.setText("5th Subject");
        GradeComputer.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, -1, -1));
        GradeComputer.add(f17, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, 100, 40));

        jLabel82.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel82.setText("7th Subject");
        GradeComputer.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 160, -1, -1));

        jLabel83.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel83.setText("First Quarter");
        jLabel83.setToolTipText("");
        GradeComputer.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        GradeComputer.add(s17, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 320, 100, 40));
        GradeComputer.add(s16, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 100, 40));

        jLabel84.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel84.setText("7th Subject");
        GradeComputer.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 280, -1, -1));

        jLabel85.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel85.setText("6th Subject");
        GradeComputer.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, -1, -1));

        jLabel86.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel86.setText("5th Subject");
        GradeComputer.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, -1, -1));
        GradeComputer.add(s15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 100, 40));
        GradeComputer.add(s14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 100, 40));

        jLabel87.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel87.setText("4th Subject");
        GradeComputer.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, -1));
        GradeComputer.add(s13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 100, 40));

        jLabel88.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel88.setText("3rd Subject");
        GradeComputer.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));
        GradeComputer.add(s12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 100, 40));

        jLabel89.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel89.setText("2nd Subject");
        GradeComputer.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));
        GradeComputer.add(s11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 100, 40));

        jLabel90.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel90.setText("1st Subject");
        GradeComputer.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        jLabel91.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel91.setText("Second Quarter");
        GradeComputer.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        bt2.setText("Calculate Second Quarter");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        GradeComputer.add(bt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 290, -1, -1));

        out1.setEditable(false);
        out1.setToolTipText("");
        GradeComputer.add(out1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 200, 83, 32));

        out2.setEditable(false);
        out2.setToolTipText("");
        GradeComputer.add(out2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 320, 83, 32));

        bt1.setText("Calculate First Quarter");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        GradeComputer.add(bt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 160, -1, -1));

        jTextField1.setEditable(false);
        GradeComputer.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 190, 160, 40));

        jButton6.setText("Calculate First & Second Quarter");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        GradeComputer.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 160, -1, -1));

        jLabel113.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel113.setText("First Semester");
        GradeComputer.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 260, -1));
        GradeComputer.add(t11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 100, 40));

        jLabel92.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel92.setText("1st Subject");
        GradeComputer.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, -1, -1));

        jLabel93.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel93.setText("2nd Subject");
        GradeComputer.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, -1, -1));
        GradeComputer.add(t12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 100, 40));
        GradeComputer.add(t14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 100, 40));

        jLabel94.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel94.setText("4th Subject");
        GradeComputer.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, -1, -1));
        GradeComputer.add(t13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 100, 40));

        jLabel95.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel95.setText("3rd Subject");
        GradeComputer.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, -1, -1));
        GradeComputer.add(t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 500, 100, 40));

        jLabel96.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel96.setText("6th Subject");
        GradeComputer.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, -1, -1));
        GradeComputer.add(t15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 100, 40));

        jLabel97.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel97.setText("5th Subject");
        GradeComputer.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, -1, -1));
        GradeComputer.add(t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 500, 100, 40));

        jLabel98.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel98.setText("7th Subject");
        GradeComputer.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, -1, -1));

        jLabel99.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel99.setText("First Quarter");
        jLabel99.setToolTipText("");
        GradeComputer.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));
        GradeComputer.add(p17, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 620, 100, 40));
        GradeComputer.add(p16, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 620, 100, 40));

        jLabel100.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel100.setText("7th Subject");
        GradeComputer.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 580, -1, -1));

        jLabel101.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel101.setText("6th Subject");
        GradeComputer.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 580, -1, -1));

        jLabel102.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel102.setText("5th Subject");
        GradeComputer.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 580, -1, -1));
        GradeComputer.add(p15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 620, 100, 40));
        GradeComputer.add(p14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 620, 100, 40));

        jLabel103.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel103.setText("4th Subject");
        GradeComputer.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, -1, -1));
        GradeComputer.add(p13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 100, 40));

        jLabel104.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel104.setText("3rd Subject");
        GradeComputer.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, -1, -1));
        GradeComputer.add(p12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 620, 100, 40));

        jLabel105.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel105.setText("2nd Subject");
        GradeComputer.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, -1, -1));
        GradeComputer.add(p11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 620, 100, 40));

        jLabel106.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel106.setText("1st Subject");
        GradeComputer.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, -1, -1));

        jLabel107.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel107.setText("Second Quarter");
        GradeComputer.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, -1, -1));

        bt3.setText("Calculate Second Quarter");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        GradeComputer.add(bt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 590, -1, -1));

        out3.setEditable(false);
        out3.setToolTipText("");
        GradeComputer.add(out3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 500, 83, 32));

        out4.setEditable(false);
        out4.setToolTipText("");
        GradeComputer.add(out4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 620, 83, 32));

        bt4.setText("Calculate First Quarter");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });
        GradeComputer.add(bt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 460, -1, -1));

        jTextField2.setEditable(false);
        GradeComputer.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 490, 160, 40));

        jButton7.setText("Calculate First & Second Quarter");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        GradeComputer.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 460, -1, -1));

        jLabel114.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel114.setText("Second Semester");
        GradeComputer.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 320, -1));

        getContentPane().add(GradeComputer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 1590, 980));
        GradeComputer.getAccessibleContext().setAccessibleName("");
        GradeComputer.getAccessibleContext().setAccessibleDescription("");

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Plain White.jpg"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 10, 1920, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked

        new HomePage().setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     new  grade().setVisible(true);



    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
          try {
        if (s11.getText().isEmpty() || s12.getText().isEmpty() || s13.getText().isEmpty() || 
            s14.getText().isEmpty() || s15.getText().isEmpty() || s16.getText().isEmpty() || 
            s17.getText().isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(this, "You have a missing Grade, Please Input a Grade!");
            return;
        }

        int a = Integer.parseInt(s11.getText());
        int b = Integer.parseInt(s12.getText());
        int c = Integer.parseInt(s13.getText());
        int d = Integer.parseInt(s14.getText());
        int e = Integer.parseInt(s15.getText());
        int f = Integer.parseInt(s16.getText());
        int g = Integer.parseInt(s17.getText());
         if (a > 99 || b > 99 || c > 99 || d > 99 || e > 99 || f > 99 || g > 99) {
            
       javax.swing.JOptionPane.showMessageDialog(this, "Grades cannot exceed 100. Please enter valid grades.");
        return;
    }
        

        int result = (a + b + c + d + e + f + g) / 7;
        out2.setText(String.valueOf(result));

    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter valid numbers only!");
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
 try {
        if (f11.getText().isEmpty() || f12.getText().isEmpty() || f13.getText().isEmpty() || 
            f14.getText().isEmpty() || f15.getText().isEmpty() || f16.getText().isEmpty() || 
            f17.getText().isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(this, "You have a missing Grade, Please Input a Grade!");
            return;
        }

        int a = Integer.parseInt(f11.getText());
        int b = Integer.parseInt(f12.getText());
        int c = Integer.parseInt(f13.getText());
        int d = Integer.parseInt(f14.getText());
        int e = Integer.parseInt(f15.getText());
        int f = Integer.parseInt(f16.getText());
        int g = Integer.parseInt(f17.getText());

      if (a > 99 || b > 99 || c > 99 || d > 99 || e > 99 || f > 99 || g > 99) {
            
       javax.swing.JOptionPane.showMessageDialog(this, "Grades cannot exceed 100. Please enter valid grades.");
        return;
    }
        
         

       

        int result = (a + b + c + d + e + f + g) / 7;
        out1.setText(String.valueOf(result));
        
          

    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter valid numbers only!");
    }


        // TODO add your handling code here:
    }//GEN-LAST:event_bt1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
  int a = Integer.parseInt(out1.getText());
        int b = Integer.parseInt(out2.getText());
        
        int cal = (a+b)/2;
        jTextField1.setText(""+cal);
        
        
        
        






        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        
        
        try {
        if (p11.getText().isEmpty() || p12.getText().isEmpty() || p13.getText().isEmpty() || 
            p14.getText().isEmpty() || p15.getText().isEmpty() || p16.getText().isEmpty() || 
            p17.getText().isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(this, "You have a missing Grade, Please Input a Grade!");
            return;
        }

        int a = Integer.parseInt(p11.getText());
        int b = Integer.parseInt(p12.getText());
        int c = Integer.parseInt(p13.getText());
        int d = Integer.parseInt(p14.getText());
        int e = Integer.parseInt(p15.getText());
        int f = Integer.parseInt(p16.getText());
        int g = Integer.parseInt(p17.getText());

       if (a > 99 || b > 99 || c > 99 || d > 99 || e > 99 || f > 99 || g > 99) {
            
       javax.swing.JOptionPane.showMessageDialog(this, "Grades cannot exceed 100. Please enter valid grades.");
        return;
    }
        
         

       

        int result = (a + b + c + d + e + f + g) / 7;
        out4.setText(String.valueOf(result));

    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter valid numbers only!");
    }

    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        // TODO add your handling code here:
        try {
        if (t11.getText().isEmpty() || t12.getText().isEmpty() || t13.getText().isEmpty() || 
            t14.getText().isEmpty() || t15.getText().isEmpty() || t16.getText().isEmpty() || 
            t17.getText().isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(this, "You have a missing Grade, Please Input a Grade!");
            return;
        }

        int a = Integer.parseInt(t11.getText());
        int b = Integer.parseInt(t12.getText());
        int c = Integer.parseInt(t13.getText());
        int d = Integer.parseInt(t14.getText());
        int e = Integer.parseInt(t15.getText());
        int f = Integer.parseInt(t16.getText());
        int g = Integer.parseInt(t17.getText());

       if (a > 99 || b > 99 || c > 99 || d > 99 || e > 99 || f > 99 || g > 99) {
            
       javax.swing.JOptionPane.showMessageDialog(this, "Grades cannot exceed 100. Please enter valid grades.");
        return;
    }
        
         

       

        int result = (a + b + c + d + e + f + g) / 7;
        out3.setText(String.valueOf(result));

    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter valid numbers only!");
    }

        
        
        
        
        
    }//GEN-LAST:event_bt4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
         int a = Integer.parseInt(out3.getText());
        int b = Integer.parseInt(out4.getText());
        
        int cal = (a+b)/2;
        jTextField2.setText(""+cal);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private java.awt.Panel GradeComputer;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JTextField f11;
    private javax.swing.JTextField f12;
    private javax.swing.JTextField f13;
    private javax.swing.JTextField f14;
    private javax.swing.JTextField f15;
    private javax.swing.JTextField f16;
    private javax.swing.JTextField f17;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField out1;
    private javax.swing.JTextField out2;
    private javax.swing.JTextField out3;
    private javax.swing.JTextField out4;
    private javax.swing.JTextField p11;
    private javax.swing.JTextField p12;
    private javax.swing.JTextField p13;
    private javax.swing.JTextField p14;
    private javax.swing.JTextField p15;
    private javax.swing.JTextField p16;
    private javax.swing.JTextField p17;
    private javax.swing.JTextField s11;
    private javax.swing.JTextField s12;
    private javax.swing.JTextField s13;
    private javax.swing.JTextField s14;
    private javax.swing.JTextField s15;
    private javax.swing.JTextField s16;
    private javax.swing.JTextField s17;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t13;
    private javax.swing.JTextField t14;
    private javax.swing.JTextField t15;
    private javax.swing.JTextField t16;
    private javax.swing.JTextField t17;
    // End of variables declaration//GEN-END:variables
}
